name: CI/CD
on:
  push:
    branches: '**'
jobs:
  github-package:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GHCR }}
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          docker build -t ghcr.io/vicovillca/proyectoobi/backend-tutor -f back_end/Tutor/Dockerfile back_end/Tutor/
      - name: Push Docker images to registry
        run: |
          docker push ghcr.io/vicovillca/proyectoobi/backend-tutor
